{
 "title": "CMS Summary Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "web_host",
    "query": {
     "query": "label_values(probe_http_status_code,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status - $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host\"}[$__interval]"
    }
   ]
  },
  {
   "title": "MySql Status - $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=~\"$host\"}[$__interval]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PHP-FPM Status - $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{instance=~\"$host\"}[$__interval]"
    }
   ]
  },
  {
   "title": "Site Status Code - $web_host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$web_host\"}[$__interval]",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}