sources:
  file_nginx_access_logs:
    type: file
    include:
      - /var/log/nginx/access.log
      - /var/log/nginx/*_access_log
  file_nginx_error_logs:
    type: file
    include:
      - /var/log/nginx/error.log
      - /var/log/nginx/*_error_log
  file_php-fpm_logs:
    type: file
    include:
      - /var/log/php-fpm/error.log
  file_mysql_logs:
    type: file
    include:
      - /var/log/mysql/mysqld.log

transforms:
  nginx_logs:
    type: remap
    inputs:
      - file_nginx_access_logs
      - file_nginx_error_logs
    source: >-
      . |= parse_nginx_log!(.message, "combined")

      .app_name = "nginx"
  php-fpm_logs:
    type: remap
    inputs:
      - file_php-fpm_logs
    source: >-
      . |= parse_regex!(.message, r'\[(?P<event_date>\d+\-\w+\-\d+\s\d+\:\d+\:\d+)\] (?P<event_severity>\w+)\: (?P<event_message>.*)$')

      .app_name = "php-fpm"
  mysql_logs:
    type: remap
    inputs:
      - file_mysql_logs
    source: >-
      . |= parse_regex!(.message, r'(?P<event_date>\d+-\d+-\d+T\d+:\d+:\d+\.\d+.) (?P<event_thread>\d) \[(?P<event_label>\w+)\] \[(?P<event_err_code>\w+-\d+)\] \[(?P<event_subsystem>\w+)\] (?P<event_message>.*)$')

      .app_name = "mysql"

sinks:
  elastic:
    type: elasticsearch
    inputs:
      - nginx_logs
      - php-fpm_logs
      - mysql_logs
    endpoints:
      - http://promvm-1.home.local:9200
    auth:
      strategy: "basic"
      user: "elastic"
      password: "47v4H9JFktoj-yE=nUg="
    bulk:
      index: "ecs-vector-{{ .app_name }}-%Y-%m-%d"
#  my_sink_console:
#    type: console
#    encoding:
#      codec: json
#    inputs:
#      - nginx_logs
#      - php-fpm_logs
#      - mysql_logs
#    target: stdout