---
- name: Download php_fpm_exporter binary to local folder
  become: false
  ansible.builtin.get_url:
    url: "{{ php_fpm_exporter_binary_url }}"
    dest: "{{ php_fpm_exporter_archive_path }}/php_fpm_exporter"
    mode: '0644'
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost

- name: Propagate php_fpm_exporter binaries
  ansible.builtin.copy:
    src: "{{ php_fpm_exporter_archive_path }}/php_fpm_exporter"
    dest: "{{ php_fpm_exporter_binary_install_dir }}/php_fpm_exporter"
    mode: '0755'
    owner: root
    group: root
  notify: restart php_fpm_exporter

- name: Copy the php_fpm_exporter systemd service file
  ansible.builtin.template:
    src: php_fpm_exporter.service.j2
    dest: /etc/systemd/system/php_fpm_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart php_fpm_exporter

- name: Ensure php_fpm_exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: php_fpm_exporter
    enabled: true
    state: started