networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "root"
    volumes:
      - ../grafana/data:/var/lib/grafana
      - ../grafana/provisioning:/usr/share/grafana/conf/provisioning:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: "http://${HOSTNAME}.home.local:3000"
      GF_SERVER_DOMAIN: "home.local"
      GF_PATHS_PROVISIONING: /usr/share/grafana/conf/provisioning
    ports:
      - 3000:3000
    restart: always
    networks:
      - monitoring
#    environment:
#      TZ: "Europe/Moscow"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/mnt/config/loki-local-config.yaml
    restart: always
    volumes:
      - ../loki:/mnt/config:rw
    ports:
    - "3100:3100"
    networks:
      - monitoring