---
- name: Restart php_fpm_exporter
  listen: "restart php_fpm_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: php_fpm_exporter
    state: restarted
  when:
    - not ansible_check_mode