{
 "title": "PHP-FPM 2",
 "description": "PHP-FPM detailed page for single FPM pool.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(phpfpm_accepted_connections_total,job)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(phpfpm_accepted_connections_total{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PHP FPM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PHP-FPM Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{instance=~\"^$host$\", job=~\"$job$\"}"
    }
   ]
  },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(phpfpm_accepted_connections_total{instance=~\"^$host$\", job=~\"$job$\"}[$Interval])",
     "legendFormat": "Accepted Connections Rate"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "phpfpm_active_max_processes{instance=~\"^$host$\", job=~\"$job$\"}",
     "legendFormat": "Max Active"
    },
    {
     "expr": "phpfpm_processes_total{instance=~\"^$host$\", job=~\"$job$\",state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "phpfpm_processes_total{instance=~\"^$host$\", job=~\"$job$\",state=\"idle\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "timeseries",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(phpfpm_slow_requests_total{instance=~\"^$host$\", job=~\"$job$\"}[$Interval])",
     "legendFormat": "Slow Requests Rate "
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "phpfpm_listen_queue_connections{instance=~\"^$host$\"}",
     "legendFormat": "Queue"
    },
    {
     "expr": "phpfpm_listen_queue_length_connections{instance=~\"^$host$\", job=~\"$job$\"}",
     "legendFormat": "Queue Length"
    }
   ]
  }
 ]
}