networks:
  monitoring:
    driver: bridge

volumes:
  elastic_vol:
    driver: local

services:
  elastic:
    image: elasticsearch:8.15.3
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD='47v4H9JFktoj-yE=nUg='
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_vol:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - monitoring

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_PUBLICBASEURL: 'http://promvm-1.home.local:5601'
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
      ELASTICSEARCH_SSL_VERIFICATIONMODE: 'none'
      ELASTICSEARCH_USERNAME: 'kibana'
      ELASTICSEARCH_PASSWORD: 'v_im5wel*NPpymxdXfxR'
    ports:
      - 5601:5601
    networks:
      - monitoring
    depends_on:
      - elastic

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/:rw
    ports:
      - 5044:5044
    environment:
#       MONITORING_ENABLED: false
      monitoring.enabled: false
    networks:
      - monitoring
    depends_on:
      - elastic