global:
  scrape_interval: 5s
  external_labels:
    site: prod

remote_write:
  - url: http://192.168.68.119:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

scrape_configs:
  - job_name: 'cms_nginx'
    static_configs:
      - targets:
          - 192.168.68.122:9113

  - job_name: 'cms_mysql'
    static_configs:
      - targets:
          - 192.168.68.122:9104

  - job_name: 'cms_node'
    static_configs:
      - targets:
          - 192.168.68.122:9100

  - job_name: 'cms_php'
    static_configs:
      - targets:
          - 192.168.68.122:8181

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://mysite.com    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.68.119:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['192.168.68.119:9115']